.TH ILOGIN 1
.SH NAME
ilogin - login program
.SH SYNOPSIS
.B ilogin 
.SH DESCRIPTION
simple root login client used by sud(1)
.SH FILES
.IP "\fI/etc/issue.suz\fR"
\&\fBilogin\fR issue file
.IP "\fI/etc/motd.suz\fR"
\&\fBilogin\fR motd file
.SH SEE ALSO
.IP "\fIsud\fR\|(1)"
super user daemon 
.IP "\fIsuz\fR\|(1)"
suz client
