.TH SUZ 1
.SH NAME
suz \d- suz client 
.SH SYNOPSIS
.B suz [-i] [-n] [-p \fIsockfile\fR]
.SH DESCRIPTION
suz is a client for sud daemon 
.SH OPTIONS
.B -i
open an interactive session
.TP
.B -n
do not try to open an interactive session
.TP
.B -p \fIsockfile\fR 
use this option to connect to this socket file
.SH SEE ALSO
.IP "\fIsud\fR\|(1)"
super user daemon
.IP "\fIilogin\fR\|(1)"
super user interface program
